source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 1.3.3'
pod 'MBProgressHUD', '~> 0.8'
pod 'GFramework',:git=>"https://code.slightech.com/robinge/gframework.git"