source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'
# ignore all warnings from all pods
inhibit_all_warnings!
pod 'AFNetworking', '~> 1.3.3'
pod 'MBProgressHUD', '~> 0.8'
pod 'ZBUtilities', '~> 0.0.4'